### PR TITLE
import lazy annotation

### PR DESCRIPTION
**Pull request by janwijbrand**
ping @thefunny42

### CODE REVIEW

**Comment by icemac** [comment]
@janwijbrand Maybe the change I made in [grokcore.annotation](https://github.com/zopefoundation/grokcore.annotation/pull/2/commits/0adf85f494221d544d91fae90c7b199c48a346b4) help here, too to make TravisCI happy.

**Comment by gyst** [comment]
@icemac the changes you made to `.travis.cfg` in `grokcore.annotation` don't apply here, because 

-  this package is not yet python3 compatible (see #3)
- using a `pip install` instead of buildout precludes getting the fork of `grokcore.annotation` that this is about (though actually merging something depending on fork should be done only after the fork has been merged and released, and then the fork here in `buildout.cfg` should be removed...)

I've made another fix in #6 .

**Comment by jamadden** [comment]
> using a pip install instead of buildout precludes getting the fork of grokcore.annotation

Just add `pip install git+https://path/to/git@branch#egg=egg.name` to the install section to have pip handle the fork.

**Comment by gyst** [comment]
I've made a PR in #6 against this branch that makes it green on Travis.

**Pull request merged**
